baseURL: "https://loganmarchione.com"
languageCode: "en-us"
title: Logan Marchione
paginate: 10

permalinks:
  posts: /:year/:month/:title/

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

outputs:
    home:
        - HTML
        - RSS
        - JSON

minify:
    disableXML: true
    minifyOutput: false

module:
  imports:
    - path: github.com/adityatelange/hugo-PaperMod
    - path: github.com/foo-dogsquared/hugo-mod-simple-icons
    - path: github.com/loganmarchione/homelab-svg-assets
      mounts:
        - source: assets
          target: assets/svg/homelab-svg-assets

deployment:
  targets:
    - name: loganmarchione.dev
      URL: "s3://loganmarchione-dev?region=us-east-2"
      cloudFrontDistributionID: CLOUDFRONT_DISTRIBUTION_DEV
  matchers:
    # cached with gzip compression enabled
    - pattern: "^.+\\.(js|css|svg|ttf)$"
      cacheControl: "max-age=86400, private, must-revalidate"
      gzip: true
    # cached with gzip compression disabled
    - pattern: "^.+\\.(atom|bmp|gif|ico|jpeg|jpg|pdf|png|rss|tiff|woff|woff2|zip)$"
      cacheControl: "max-age=86400, private, must-revalidate"
      gzip: false
    # sitemap gets a special content-type header
    - pattern: "^sitemap\\.xml$"
      contentType: "application/xml"
      gzip: true
    # not cached with gzip compression enabled
    - pattern: "^.+\\.(html|json|xml)$"
      gzip: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: "Logan Marchione"
    description: "Logan Marchione"
    author: Me
    #images: ["<link or path of image for opengraph, twitter-cards>"]

    defaultTheme: auto
    disableThemeToggle: false

    ShowReadingTime: true
    ShowWordCount: true
    ShowShareButtons: true
    disableSpecial1stPost: true
    comments: false
    hidemeta: false
    ShowToc: true
    TocOpen: false
    DateFormat: "2006-01-02"

    assets:
        disableHLJS: true
        disableFingerprinting: false
        favicon: "/assets/favicon/favicon_loganmarchione_logo.svg"
        favicon16x16: "/assets/favicon/favicon_loganmarchione_logo.svg"
        favicon32x32: "/assets/favicon/favicon_loganmarchione_logo.svg"
        apple_touch_icon: "/assets/favicon/apple-touch-icon.png"
        safari_pinned_tab: "/assets/favicon/favicon_loganmarchione_logo.svg"

    label:
        text: "Logan Marchione"
        icon: /assets/favicon/favicon_loganmarchione_logo.svg
        iconHeight: 35

    # home-info mode
#    homeInfoParams:
#        Title: "Hi there \U0001F44B"
#        Content: >
#            My name is Logan Marchione, and this is my sandbox on the web to learn about the internet, crypto{graphy,currency}, Linux, hosting, code, etc...
#            
#            - I also use this space to share and document ideas for future reference.
#            
#            - I hope you find something of value here! Enjoy!

#    socialIcons:
#        - name: RSS
#          url: "index.xml"

    cover:
        hidden: false
        hiddenInList: false
        hiddenInSingle: false
        linkFullImages: false

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

menu:
    main:
        - identifier: about
          name: About
          url: /about
          weight: 20
#        - identifier: contact
#          name: Contact
#          url: /contact
#          weight: 30
        - identifier: privacy
          name: Privacy
          url: /privacy
          weight: 30
        - identifier: search
          name: Search
          url: /search
          weight: 30
#        - identifier: categories
#          name: Categories
#          url: /categories/
#          weight: 50
        - identifier: rss
          name: RSS
          url: /index.xml
          weight: 60
#        - identifier: posts
#          name: All posts
#          url: posts
#          weight: 70

privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true
