# Config file overrides UI settings

[build]
  publish = "public/"
  command = "hugo --gc --baseURL=https://${BASE_URL}"

[build.environment]
  HUGO_VERSION = "0.92.1"

[context.dev]
  environment = { BASE_URL = "loganmarchione.dev" }
 
[context.master]
  environment = { BASE_URL = "loganmarchione.com" }

# Rewrites (because of HTTP 200 code)
[[redirects]]
  from = "/feed"
  to = "/index.xml"
  status = 200
[[redirects]]
  from = "/feed/"
  to = "/index.xml"
  status = 200
