name: CI/CD

on:
  push:
    branches:
      - master

env:
  DEV_URL: loganmarchione.dev
  PRD_URL: loganmarchione.com

jobs:
  deploy:
    name: Deploy

    runs-on: ubuntu-latest

    steps:
    - name: Check out the codebase
      uses: actions/checkout@v2
      with:
          submodules: true
          fetch-depth: 0

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: 'latest'

    - name: This is a test
      run: ls -la

    - name: Build
      run: hugo --gc --baseURL=${{ env.DEV_URL}}

    - name: This is a test
      run: |
        ls -la
        rsync --version
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy_key
        chmod -R 700 ~/.ssh
        chmod 600 ~/.ssh/deploy_key
        ls -la ~/.ssh

    - name: Rsync deployment
      run: |
        rsync -avz -e "ssh -i ~/.ssh/deploy_key -p ${{ secrets.DEPLOY_PORT }}" --delete public/ ${{ env.DEPLOY_USER }}@${{ env.DEV_URL }}:/var/www/test