name: CI/CD

on:
  push:
    branches:
      - master

env:
  URL: loganmarchione.dev

jobs:
  deploy:
    name: Deploy

    runs-on: ubuntu-latest

    steps:
    - name: Check out the codebase
      uses: actions/checkout@v2
      with:
          submodules: true
          fetch-depth: 0

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: 'latest'

    - name: Build
      run: hugo --gc --baseURL="https://${{ env.URL }}"

    - name: Deploy
      run: hugo deploy --force --maxDeletes -1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}